# -*- coding: utf-8 -*-
"""
Created on Tue Apr 14 08:42:00 2021
Read json (generated by the online annotation platform supervise.ly) and extract the frames from the selected video 
Annotation is composed by the initial and final frame for each surgical phase
@author: Rogerio Nespolo
"""
import cv2
import json
import os
filename = '' #Video file corresponding to the annotation performed by surgeons
filename_save = filename.replace('.','')
cap = cv2.VideoCapture(filename)
fps = (cap.get(5))
cap.set(cv2.CAP_PROP_FPS, fps)
success,image = cap.read()

with open(filename + '.json') as json_file:
    data = json.load(json_file)
    for p in data['tags']:
        phase = p['name']        #read the surgical phase and its framerange
        frameRange = p['frameRange']
        phase_begin = frameRange[0] #identify the beginning and the end of the current surgical phase
        phase_end = frameRange[1]
        os.makedirs(phase)  #creates the folder for the current surgical phase frames to be saved

        cap.set(cv2.CAP_PROP_POS_FRAMES, phase_begin) #set current frame at the beginning of the surgical phase
        count = phase_begin
        print(success)    
        while count <= phase_end: #Go over the frames until surgical phases end 
            cap.set(cv2.CAP_PROP_POS_FRAMES, count+1)
            print(count)
            print(phase)
            print(phase_end)
            cv2.imwrite(str(phase) +'/' '%s_%s_%d.png'%(phase, filename_save , count), image) 
            success, image = cap.read()
            count += 1

            
            